# Generated by Django 3.0.6 on 2020-06-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=22, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_short', models.CharField(max_length=3, unique=True)),
                ('currency_long', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostingText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booking', models.DateField()),
                ('date_imported', models.DateField(auto_now_add=True)),
                ('optionee', models.CharField(max_length=100)),
                ('optionee_iban', models.CharField(max_length=22)),
                ('optionee_bic', models.CharField(max_length=11)),
                ('figure', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(max_length=378)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Currency')),
                ('posting_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.PostingText')),
            ],
        ),
    ]
