# Generated by Django 3.0.7 on 2020-06-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_auto_20200613_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bic', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='optionee',
            name='bic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Bic'),
        ),
    ]
