# Generated by Django 3.0.7 on 2020-06-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_auto_20200629_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionee',
            name='iban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Account'),
        ),
    ]
