# Generated by Django 3.0.6 on 2020-06-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='booking_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.BookingStatus'),
        ),
    ]
