# Generated by Django 3.0.6 on 2020-06-13 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_statement_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optionee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('iban', models.CharField(max_length=22, unique=True)),
                ('bic', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booking', models.DateField()),
                ('date_imported', models.DateField(auto_now_add=True)),
                ('figure', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reference', models.CharField(max_length=378)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Currency')),
                ('optionee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploader.Optionee')),
            ],
        ),
        migrations.RemoveField(
            model_name='statement',
            name='account',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='posting_text',
        ),
        migrations.DeleteModel(
            name='BookingStatus',
        ),
        migrations.DeleteModel(
            name='PostingText',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
    ]
