# Generated by Django 3.0.7 on 2020-07-14 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_auto_20200629_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='booking_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uploader.BookingType'),
            preserve_default=False,
        ),
    ]
