# Generated by Django 3.0.7 on 2020-08-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_auto_20200714_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionee',
            name='bic',
        ),
        migrations.RemoveField(
            model_name='optionee',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='optionee',
        ),
        migrations.DeleteModel(
            name='Bic',
        ),
        migrations.DeleteModel(
            name='BookingType',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Iban',
        ),
        migrations.DeleteModel(
            name='Optionee',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
